### ISSUE TITLE
ftp link not working

### ISSUE THREAD

**Issue by mandarwce** [latextemplates/LNCS#13]
I am not able to access following links
ftp://ftp.springer.de/pub/tex/latex/llncs/latex2e/llncs.cls
ftp://ftp.springer.de/pub/tex/latex/llncs/latex2e/splncs03.bst

Requests are just timing out.

**Comment by koppor** [comment]
Does the link ftp://ftp.springer.de/pub/tex/latex/llncs/latex2e/llncs2e.zip work for you?

This is linked from http://www.springer.com/computer/lncs?SGWID=0-164-6-793341-0

I currently do not know where else to get the files from. Sharelatex seems to provide them...

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=31897#47 for the reasons why I cannot offer these files directly.

**Comment by mandarwce** [comment]
ftp://ftp.springer.de/pub/tex/latex/llncs/latex2e/llncs2e.zip - Also doesn't work!
I understand the license issue,
Anyways, thank you for the help!

**Comment by koppor** [comment]
Locally, the ftp link works.

You could try http://www.net2ftp.com/. It worked fine here, too.

I think, https://github.com/bhzaeri/llncs2e/tree/781e514642b590d6300f584bd6ba25d36174d980 provides the files using http. I assume, it is not approved by Springer, but could help in your

**Comment by mandarwce** [comment]
It worked using net2ftp. Thank you for the help.

**Comment by limberc** [comment]
Hi there, I also cannot access ftp://ftp.springer.de/pub/tex/latex/llncs/latex2e/llncs2e.zip
And I failed to use net2ftp.

Can anyone give me a hint how to use it?

**Comment by koppor** [comment]
Maybe, it is a local issue. My Firefox in Germany using UnityMedia as internet provider opens llncs2e.zip without issues.

Note that the link is the same as linked from https://www.springer.com/gp/computer-science/lncs/conference-proceedings-guidelines --> "Templates, sample files & useful links".
