### ISSUE TITLE
Switch to svproc.cls

### ISSUE THREAD

**Issue by koppor** [latextemplates/LNCS#19]
According to https://www.springer.com/gp/authors-editors/conference-proceedings/conference-proceedings-guidelines, the `svproc.cls` class is the class to use. In the [ProSci_TeX.zip](ftp://ftp.springernature.com/cs-proceeding/svproc/templates/ProcSci_TeX.zip), there is an `author.tex` using `svproc.cls`.

However, http://www.springer.com/de/it-informatik/lncs/conference-proceedings-guidelines still links to the `llncs.cls`. Thus, no switch necessary.

**Comment by amandeep0429** [comment]
i am facing same problem. I have got an error that svproc.cls not found while running author.tex from springer. Please suggest me solution. I am new to latex

**Comment by koppor** [comment]
@amandeep0429 Please refine your problem.

I tried to repodruce:

Download ftp://ftp.springernature.com/cs-proceeding/svproc/templates/ProcSci_TeX.zip (from mirror http://www.logdynamics.de/fileadmin/Upload/Dokumente/LDIC_2020/ProcSci_TeX.zip)


pdflatex:

```cmd
$ pdflatex author.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (MiKTeX 20.7)
entering extended mode
(author.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-08-07>

! LaTeX Error: File `svproc.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name:
! Emergency stop.
<read *>

l.14

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on author.log.
```

Inspect the zip archive. In `../styles`, there is `svproc.cls`. I copied that `.cls` file to the directory `template`. Now, pdflatex works

**Comment by amandeep0429** [comment]
yes, it worked. Thank you very much @koppor

**Comment by sob05001** [comment]
Thanks @koppor, it worked.
