### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by burdges** [latextemplates/LNCS#2]
I though `llncs.cls` could not be redistributed : 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=31897
Ain't clear they'd ever complain either, of course.

**Comment by koppor** [comment]
Thank you for the pointer. For personal reference, I include the important statement from [comment 47 of debian bug 31897](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=31897#47), where http://www.springer.de/author/tex/help-book.html (404 today) is quoted:

```
Copyright policy

All macro packages[1] have been developed by Springer-Verlag
Heidelberg as a free service to its authors and editors preparing
texts for publication by Springer-Verlag.

User's guides and macros may be copied and passed on to other
Springer authors, but may not be sold or placed on any mailserver
other than the one maintained by Springer-Verlag. Our macro packages
may not be incorporated into other TeX macro packages or used
commercially unless permission has been granted by Springer-Verlag.
```

The updated version of this template fetches the files from Springer's FTP server locally, which should be in line with their policy.

**Comment by vanto** [comment]
:+1: - - though github is certainly not a mailserver ;)
