### ISSUE TITLE
Unable to copy numbers

### ISSUE THREAD

**Issue by duichwer** [latextemplates/LNCS#22]
Hi,

I used your template for creating an document. Now I have the problem that it is not possible to copy numbers out of the text from the created pdf-file.
I always receive the question-mark-box after copying some numbers inside text.

Numbers I added with the package siunitx are copyable.
I only added this package and changed nothing else.

**Comment by koppor** [comment]
I tried with following LaTeX source

```
Numbers can written using the siunitx package like that:
\SI{100}{\km\per\hour}
or just plain \LaTeX{}:
$100 \frac{\mathit{km}}{h}$.
```

See also https://github.com/latextemplates/LNCS/commit/650fa382882bc72a8f99995c3d808af61cafc783.

It produces following PDF:

![grafik](https://user-images.githubusercontent.com/1366654/38890465-c5a6f07c-4281-11e8-8ea2-60fb5fbab3de.png)

Copy and paste leads to:

```
Numbers can written using the siunitx package like that: 100
km
h
or just plain
L
A T E X: 100 km
h
.
```

What is your input? Did you use other numbers?

**Comment by duichwer** [comment]
Hi,
I've written my numbers inline as Text. 
But I will try it inside the math environment.

**Comment by koppor** [comment]
Do you use the latest release (1.7.0) or the master branch?

Which system do you use? I tried with following setup:

    $ lualatex --version
    This is LuaTeX, Version 1.0.4 (TeX Live 2017/W32TeX)

I changed the test text to

    Numbers can written plain text (such as 100), by using the siunitx package like that:

I tried SumatraPDF. Now I tried Acrobat Reader, too. Result:

    Numbers can written plain text (such as 100), by using the siunitx package
    like that: 100 km
    h , or by using plain LATEX (and math mode): 100km
    h .

Does this also happen with the PDF compiled using CircleCI / the Docker image? I tried https://latextemplates.github.io/LNCS/paper.pdf at Firefox and I cannot copy numbers. Result:

    Numbers can written plain text (such as
    

With http://latextemplates.github.io/LNCS/paper-newtx.pdf, it works.

With https://latextemplates.github.io/LNCS/paper.pdf and Acrobat Reader, I also cannot copy the numbers.

    Numbers can written plain text (such as 􀀀􀀀), by using the siunitx package
    like that: 100 km
    h , or by using plain LATEX (and math mode): 100km
    h .

So, we kind of reproduced the issue.

**Comment by duichwer** [comment]
Hi,

I use the following setup:

- Windows 10
- MikTex Distribution with recent updates,
- pdflatex to compile
- TexStudio as Editor

I used the download link in the Quick Start section in the `README` file of the master branch.
Afterwards I downloaded the LNCS class and added that file to this directory.

I've also reproduced this copy-error with the plain `paper.tex` document without any modifications of mine.


I tried to copy from both files `paper-newtx.pdf` and `paper.pdf` and I was able to copy numbers inside the default GoogleChrome PDF-Preview.

When I opended both files with Acrobat Reader, I was only able to copy numbers from `paper-newtx.pdf`

For a fast workaround:

How can I switch the font to Times New Roman  with `pdflatex`?

**Comment by koppor** [comment]
You could try lualatex in case you don't want to change the font. Would be interesting if that works. (lualatex is recommended by many developers in the latex eco system)

For switching to Times (to get more space):

Change the `iftrue` to `iffalse` at https://github.com/latextemplates/LNCS/blob/50cb89e0faefe87889d7c80cc4a42527ab147fe0/paper.tex#L38

To keep the font, you could also try to replace following

```
    % better font, similar to the default springer font
    % cfr-lm is preferred over lmodern. Reasoning at http://tex.stackexchange.com/a/247543/9075
    \usepackage[%
      rm={oldstyle=false,proportional=true},%
      sf={oldstyle=false,proportional=true},%
      tt={oldstyle=false,proportional=true,variable=false},%
      qt=false%
    ]{cfr-lm}
```

by 

    \usepackage{lmodern}

Would be interesting whether `lmodern` works better than `cfr-lm`.

**Comment by duichwer** [comment]
Hi,

I switched to lualatex and now the numbers are copy-able; with `default font` and also with `Tex Gyre Termes`.

**Comment by koppor** [comment]
Forwarded to tex.stackexchange: https://tex.stackexchange.com/q/428111/9075

**Comment by koppor** [comment]
I got an answer - the fix is to switch from `cmap` to `glyphtounicode` - https://github.com/latextemplates/LNCS/commit/da71ea05ae16af964d12ea9e69ce1cd69692e4af

Can you try again with the most recent version?
