### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by marcopegoraro** [latextemplates/LNCS#26]
Hello,
I have been looking through the project files for a licensing indication, but could not find any. I would suggest to explicitly indicate the license of the project files and their terms of use.
Thank you.

**Comment by koppor** [comment]
I read https://github.com/benbalter/talks/issues/15 and will apply BSD0.

**Comment by koppor** [comment]
Fixed at https://github.com/latextemplates/LNCS/commit/272f7920d164857e7afa39da71ae79c3706ea43d
